import './globals.css'

export const metadata = {
  title: 'fe-ecosphere'
  // description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      data-color-mode="dark"
      data-light-theme="light_colorblind"
      data-dark-theme="dark"
    >
      <body className="" theme-mode="dark">
        {children}
      </body>
    </html>
  )
}
